import eslintPluginAstro from 'eslint-plugin-astro';
import tseslint from 'typescript-eslint';

const legacyGlobals = {
  window: 'readonly',
  document: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  console: 'readonly',
  fetch: 'readonly',
  setTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  clearTimeout: 'readonly',
  requestAnimationFrame: 'readonly',
  IntersectionObserver: 'readonly',
  URL: 'readonly',
  crypto: 'readonly',
  TextEncoder: 'readonly',
  Uint8Array: 'readonly',
  Array: 'readonly',
  Math: 'readonly',
  Date: 'readonly',
  JSON: 'readonly',
  String: 'readonly',
  Number: 'readonly',
  Promise: 'readonly',
  confirm: 'readonly',
  alert: 'readonly',
  location: 'readonly',
  FileReader: 'readonly',
  Image: 'readonly',
  matchMedia: 'readonly',
  Blob: 'readonly',
  cancelAnimationFrame: 'readonly',
  DOMPurify: 'readonly',
  marked: 'readonly',
  Core: 'readonly',
  Router: 'readonly',
  ParticleSystem: 'readonly',
  CursorGlow: 'readonly',
  initScrollReveal: 'readonly',
  initSkillBars: 'readonly',
  init3DTilt: 'readonly',
  initFilters: 'readonly',
  initBlogCardClicks: 'readonly',
  initProjectCardClicks: 'readonly',
  initMobileNav: 'readonly',
  initScatterReveal: 'readonly',
  initCardEffects: 'readonly',
  initFilterAnimReplay: 'readonly',
  initTypewriter: 'readonly',
  initNavBehavior: 'readonly',
  updateActiveNavLink: 'readonly',
  initSmoothScroll: 'readonly',
  initLoader: 'readonly',
  initScrollProgress: 'readonly',
};

export default [
  {
    ignores: [
      'vendor/**',
      'node_modules/**',
      'dist/**',
      'data/**',
      'e2e/fixtures/.astro/**',
      'e2e/fixtures/dist/**',
      '*.min.js',
    ],
  },
  {
    files: ['js/**/*.js', 'themes/**/*.js', 'admin/**/*.js'],
    languageOptions: { ecmaVersion: 2022, sourceType: 'script', globals: legacyGlobals },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-console': 'off',
      eqeqeq: 'warn',
      'no-eval': 'error',
      'no-implied-eval': 'error',
    },
  },
  {
    files: ['js/**/*.js', 'themes/**/*.js', 'admin/**/*.js'],
    rules: { '@typescript-eslint/no-unused-vars': 'off' },
  },
  ...tseslint.configs.recommended,
  ...eslintPluginAstro.configs.recommended,
  {
    files: ['js/**/*.js', 'themes/**/*.js', 'admin/**/*.js'],
    rules: { '@typescript-eslint/no-unused-vars': 'off' },
  },
];
