export default [
  {
    files: ['js/**/*.js', 'themes/**/*.js', 'admin/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        requestAnimationFrame: 'readonly',
        IntersectionObserver: 'readonly',
        URL: 'readonly',
        crypto: 'readonly',
        TextEncoder: 'readonly',
        Uint8Array: 'readonly',
        Array: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        JSON: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Promise: 'readonly',
        confirm: 'readonly',
        alert: 'readonly',
        location: 'readonly',
        FileReader: 'readonly',
        Image: 'readonly',
        matchMedia: 'readonly',
        Blob: 'readonly',
        cancelAnimationFrame: 'readonly',
        DOMPurify: 'readonly',
        marked: 'readonly',
        Core: 'readonly',
        Router: 'readonly',
        ParticleSystem: 'readonly',
        CursorGlow: 'readonly',
        initScrollReveal: 'readonly',
        initSkillBars: 'readonly',
        init3DTilt: 'readonly',
        initFilters: 'readonly',
        initBlogCardClicks: 'readonly',
        initProjectCardClicks: 'readonly',
        initMobileNav: 'readonly',
        initScatterReveal: 'readonly',
        initCardEffects: 'readonly',
        initFilterAnimReplay: 'readonly',
        initTypewriter: 'readonly',
        initNavBehavior: 'readonly',
        updateActiveNavLink: 'readonly',
        initSmoothScroll: 'readonly',
        initLoader: 'readonly',
        initScrollProgress: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-console': 'off',
      'eqeqeq': 'warn',
      'no-eval': 'error',
      'no-implied-eval': 'error',
    },
  },
  {
    ignores: ['vendor/**', 'node_modules/**', 'data/**', '*.min.js'],
  },
];
